version: 2
updates:
- package-ecosystem: cargo
  directory: "/"
  schedule:
    interval: weekly
    time: "00:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: reqwest
    versions:
    - 0.11.1
    - 0.11.2
  - dependency-name: serde
    versions:
    - 1.0.123
    - 1.0.124
  - dependency-name: serde_json
    versions:
    - 1.0.62
  - dependency-name: log
    versions:
    - 0.4.13
  rebase-strategy: disabled
