[package]
name = "vault-gke-helper"
version = "0.1.2"
authors = ["Yong Wen Chua <lawliet89@users.noreply.github.com>"]
edition = "2018"

[dependencies]
clap = "2.32.0"
chrono = "0.4.6"
env_logger = "0.6.1"
failure = { version = "0.1.5", features=["backtrace"] }
reqwest = "0.9.17"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
log = "0.4"
url = "1.7.2"
